# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4bcba2bdc8c51c9d72f74e21647cd209"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "pravin"
handle = "pravin"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms, write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
